# Generated by Django 4.2.6 on 2023-10-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seu_estoque_pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seu_estoque_pessoal.user'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seu_estoque_pessoal.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seu_estoque_pessoal.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
