# Generated by Django 4.2.6 on 2023-10-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seu_estoque_pessoal', '0002_produto_cliente_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seu_estoque_pessoal.user'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seu_estoque_pessoal.user'),
        ),
    ]
