# Generated by Django 4.2.6 on 2023-10-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seu_estoque_pessoal', '0003_categoria_user_fornecedor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
