# Generated by Django 4.2.6 on 2023-10-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seu_estoque_pessoal', '0004_rename_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='cliente',
            new_name='user',
        ),
    ]
